version: '3.1'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: '/app'
        volumes:
            - './app:/app'
        ports:
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
